### PR TITLE
Allowing customize NetworkView interaction (drag, cut and select)

### PR DESCRIPTION
**Pull request by danielcaceresm**
Added routed events that allows to modify the default networkview interactions (drag, cut and select).

Using them in ShaderEditor sample:

MainWindow.xaml
```xaml
<views:NetworkView Grid.Row="1" x:Name="networkView" views2:DragCanvas.PreviewDragStart="networkView_PreviewDragStart" PreviewCutLineStart="networkView_PreviewCutLineStart" PreviewSelectionRectangleStart="networkView_PreviewSelectionRectangleStart" />
```

MainWindow.xaml.cs
```csharp
        private void networkView_PreviewDragStart(object sender, PreviewDragStartEventArgs args)
        {
            var canvas = (DragCanvas)args.OriginalSource;
            args.Handled = true;
            if (args.MouseEvent.ChangedButton == MouseButton.Middle || (args.MouseEvent.ChangedButton == MouseButton.Left && Keyboard.Modifiers.HasFlag(ModifierKeys.Control)))
            {
                canvas.IsDraggingEnabled = true;
            }
            else
            {
                canvas.IsDraggingEnabled = false;
            }
        }

        private void networkView_PreviewCutLineStart(object sender, PreviewCutLineStartEventArgs args)
        {
            var networkView = (NetworkView)args.OriginalSource;
            args.Handled = true;
            if (args.MouseEvent.ChangedButton == MouseButton.Right || (args.MouseEvent.ChangedButton == MouseButton.Left && Keyboard.Modifiers.HasFlag(ModifierKeys.Shift)))
            {
                networkView.IsCutLineEnabled = true;
            }
            else
            {
                networkView.IsCutLineEnabled = false;
            }
        }

        private void networkView_PreviewSelectionRectangleStart(object sender, PreviewSelectionRectangleStartEventArgs args)
        {
            var networkView = (NetworkView)args.OriginalSource;
            args.Handled = true;
            if (args.MouseEvent.ChangedButton == MouseButton.Left && Keyboard.Modifiers == ModifierKeys.None)
            {
                networkView.IsSelectionRectangleEnabled = true;
            }
            else
            {
                networkView.IsSelectionRectangleEnabled = false;
            }
        }
```

### CODE REVIEW

**Comment by Wouterdek** [comment]
If I understand correctly, you are trying to make the mouse/keyboard buttons for dragging/cutting/selecting customizable?

**Comment by danielcaceresm** [comment]
Yes, we need to change the default mouse/keyboard buttons for dragging/cutting/selecting, and this is the way I think is less intrusive with the current behavior.

**Comment by Wouterdek** [comment]
I think there is an easier/cleaner way to implement this using the InputGestures from WPF. I've created a new PR, #93, which implements this idea. Does that one fit your usecase?

**Comment by danielcaceresm** [comment]
Hi @Wouterdek ,

Yes, this is a cleaner way to achieve this! I will comment in the PR with a little suggestion. I will close this one.

**Pull request closed without merging**
