### PR TITLE
Added endpoint grouping feature

### PR DESCRIPTION
**Pull request by FabianNitsche**
This allows optional grouping of inputs, outputs and groups itself.

### CODE REVIEW

**Comment by Wouterdek** [comment]
Ok, so here is a list of notes:

- Might not be super important, but it seems like this PR is based of an older commit or something? Because the changelog has changes from commit a25a60a. This might be fixed by rebasing it on the current master
- Couple of style notes: Put #region around reactive properties so that they can be collapsed in the editor as they are just boilerplate that clutters up the view. Also, put all properties at the top of the file, above the constructor (but below the static block, if any)
- Remove `EndpointGroup.NoGroup`. I get why you added it, but it will cause confusion. For example: 
```csharp
input.Group = null;
if(input.Group == null)
{
   // Will not run
}
```
The rest of the library uses null values, so its better to be consistent and use null here too. At some point, I will probably put C#8 nullable reference type annotations in the code instead.
- I'm not a fan of the group separator lines in EndpointGroupView. The color is the same as the selection color, while having nothing to do with selection. The usage of color here is also kind of distracting. A better solution would be to make the background of the group a semitransparant dark grey, so that it looks indented compared to the rest of the node. A bit of padding might also help separate the groups.
- I'm also not entirely convinced on the way `EndpointGroupViewModel`s are generated from `EndpointGroup`s in `NodeViewModel`, but I need to think about that one some more.

Again, thanks for your time and effort!

**Comment by FabianNitsche** [comment]
Again, bear with me on this. I am starting with git, github, ReactiveUI, DynamicData, WPF ... Sorry.

1. I do not know what I f... up there. I tried to rebase but it would not work. Should I create a new pull request with a cherry-picked branch?
2. Done.
3. Done.
4. Done.
5. Can't help you with that I guess... :D

It is rather you, who deserves the praises for such a great library, I just want to contribute back the things I have to add for my needs.

**Comment by FabianNitsche** [comment]
Concerning 1. I think I now know what went wrong there. I was merging your changeset a25a60a into my forks master and based this feature branch on it.

**Comment by Wouterdek** [comment]
Ok, so I took another look at it, and here are my notes:

In NodeViewModel:
- Add `EndpointGroupViewModelFactory` as a property and use it in `Transform()` to create group viewmodels. This allows users to swap out `EndpointGroupViewModel` for their own derived class, similar to how `ConnectionViewModel` can be replaced in `NetworkViewModel` by changing `ConnectionFactory`.
- I believe the code from `Bind(out var unorderedEndpointGroups) ...` to `... ToObservableChangeSet()` can be replaced with `.AddKey(group => group.GroupKey)`?
- Group creation is using observable cache, which might be fine, but how is order defined? As in, is there a deterministic order in which the groups will be presented on the node? 

In EndpointGroupViewModel: 
- Change constructor to (EndpointGroup, IObservableList<Endpoint>, EndpointGroupViewModelFactory). The first two arguments correspond to `node.Key` and `node.Item.List`. The last one will be the `EndpointGroupViewModelFactory` you create in `NodeViewModel`, and you can use it in the Transform() on the last line.
- I see you used Cast() in NodeViewModel, but here Transform() for VisibleInputs, VisibleOutputs. Maybe this one can be Cast() aswell?

Finally, I think the view will look better without the grey line at the top and bottom.

With these changes, I think this will be ready to merge.

**Comment by FabianNitsche** [comment]
1. Done. Although the constructor of EndpointGroupViewModel still references the DynamicData.Node in its signature for the nested endpoint groups.
2. Done.
3. Since first the groups of the inputs and than the outputs are joined into one large set, I think the groups are ordered by as they are added to the input and output collections. Where the last addition is first? But I do not really know. I experimented with sorting, by adding a IComparer<EndpointViewModel> property to the NodeViewModel. But it made things slow and the result was wobbly. I think sorting the changeset is a bad idea. Probably the resulting list should be sorted. But there I do not know how to do this.
4. Done. See 1.)
5. Done. The building of the view model tree was wrong and I had to rewrite it. This lead to simpler, more readable code, and I got rid of all the casting.
6. Done:
grafik

**Comment by FabianNitsche** [comment]
I finally added tests for the functionality. I should have done this earlier. It surfaced other bugs especially when removing endpoints. This is now fixed.

**Comment by Wouterdek** [comment]
I cloned the PR, made some small changes and merged it. Seems like github does not detect this as a merge, so I'll close this PR.

Thank you!

**Pull request closed without merging**
