### PR TITLE
Fixed a WPF issue causing binding errors.

### PR DESCRIPTION
**Pull request by FabianNitsche**
Fixes issue #97.

### CODE REVIEW

**Comment by Wouterdek** [comment]
The code looks good to me, but it might be useful to add a comment referring to issue #97 so people know why its there.

**Comment by FabianNitsche** [comment]
Sorry. Where should I put the comment?

**Comment by Wouterdek** [comment]
Above `<Style TargetType="MenuItem">` in the code, a one line comment referring to the issue.

**Comment by FabianNitsche** [comment]
Added a comment as suggested.

**Pull request merged**
