### PR TITLE
Add .NET Core 3.0 target

### PR DESCRIPTION
**Pull request by reflectronic**
This is a preliminary implementation of a .NET Core 3.0 target for NodeNetwork. However, it's probably a bad idea to merge this right now, since it has major issues that are blocked by a few outside factors.

I migrated all projects to the new 'SDK style' csproj format (using the new, in preview, `Microsoft.Net.Sdk.WindowsDesktop` SDK). I also multi-targeted each project to `netcoreapp3.0` and `net462` (frankly, I was doing some testing with this and forgot to change it back, but the downgrade still works fine - should this be kept?)

You need to install the in-preview [.NET Core 3.0 SDK](https://dotnet.microsoft.com/download/dotnet-core/3.0) in order to compile it right now (and [VS 2019 Preview](https://visualstudio.microsoft.com/vs/preview/) if you want IDE support, but `dotnet build` at the command line works fine). Right now a *lot* of this depends on the [.NET Framework Compatibility mode](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-framework-compatibility-mode) (and a lot of it also breaks because of it) - hopefully at some point all of the dependencies add a proper .NET Core 3.0 target.

image

Currently using this on .NET Core has quite a few issues that I don't have control over:
- The Reactive Extensions people ship a .NET Standard and .NET Framework target of their library in the same NuGet package. Obviously since .NET Standard doesn't have WPF stuff, that version of the library doesn't have classes like `DispatcherScheduler` that ReactiveUI depends on. Since NuGet's package resolution picks .NET Standard over .NET Framework when targeting .NET Core, the program crashes trying to load a class that doesn't exist. I got around this by manually downloading the [`System.Reactive`](https://www.nuget.org/api/v2/package/System.Reactive/4.1.3) NuGet package and copying over the assembly downloaded by the build with the .NET Framework version from the package. So we're blocked on this one until the Reactive Extensions people figure something out with this.
- ~~The XAML compiler used in the .NET Core 3.0 tooling doesn't seem to understand using a MarkupExtension as the name property in files that get loaded at runtime. I talked about this at https://github.com/Wouterdek/NodeNetwork/issues/22 and filed a bug at https://github.com/dotnet/wpf/issues/378 to resolve this. For now I just replaced all of the usages of that pattern with the actual name itself in the XAML source. When this issue becomes resolved, someone can revert https://github.com/Wouterdek/NodeNetwork/commit/bde6b0830a119c27c22bb0275bcce8194930948b and the `x:Static`s will be back. Considering this is kind of an ugly hack though, we're blocked on this one as well until the WPF guys figure something out.~~
- Something seems to be wrong with OpenGL.Net's package structure or something; I just couldn't get the OpenGL sample to compile and/or run. If anyone can figure this out, please let me know - otherwise someone should get rid of the .NET Core 3.0 target for that one.
- I have no clue if any of the tests work because none of the things that they are testing work without major coercion, so we'll have to figure that out as the above issues become resolved.

### CODE REVIEW

**Comment by Wouterdek** [comment]
Thank you for your contribution! It seems like there is still some work to be done on .NET core and the dependencies of this library before NodeNetwork can stably target .NET core. I very much appreciate the work you have done here as I know stuff like this can be very tedious. I'm going to leave this PR open for later review when the ecosystem has matured a bit.

Just out of curiosity: is there any specific reason you want/need .NET core targeting for this library?

**Comment by reflectronic** [comment]
I'm working on a [project](https://github.com/startnine) that's targeting .NET Core 3.0. For whatever reason NuGet doesn't seem to think that NodeNetwork is compatible with .NET Core even with the compatibility mode stuff, so I just decided to port the library 😃

**Comment by reflectronic** [comment]
Progress update:
The bug in WPF has been fixed (although it doesn't look like it made it into preview 4 - it works fine though in the nightlies). The other issues still stand though. I also downgraded the .NET Framework again to .NET 4.6.1 because it worked fine.

However, for whatever reason, connecting nodes is now broken in .NET Core - this is probably a .NET Core thing though because it works totally fine in .NET Framework.

**Comment by nvella** [comment]
Hi all. Has any progress been made on this as of late? It's looking like I'll need to be implementing a node editor in a Core 3 application relatively soon. Happy to make some contributions. Cheers :)

**Comment by Wouterdek** [comment]
I haven't worked on porting NodeNetwork to .net core, so there is no more progress than is written out in this thread. Quite a bit of time has passed since the last update, so new versions of the framework might have resolved the issues reflectronic mentioned. Any contributions you are willing to make on this front would be very welcome :)

**Comment by Wouterdek** [comment]
The next release will have .net core 3.1 support. See PR #55 for more information.

Thanks for your pull request!

**Pull request closed without merging**
